### ISSUE TITLE
并发测试下的问题

### ISSUE THREAD

**Issue by xqxyxchy** [yu199195/myth#27]
作者您好！
附件的图片是我并发测试的结果，2个线程就出现数据不一致了。
是我测试方式不对还是程序存在并发问题？
跑的是dmeo

![default](https://user-images.githubusercontent.com/21134578/44325831-6e6fd680-a48c-11e8-940f-c812762b3bb4.png)
![default](https://user-images.githubusercontent.com/21134578/44325844-7760a800-a48c-11e8-82ba-92591f36e985.png)
![default](https://user-images.githubusercontent.com/21134578/44325853-7fb8e300-a48c-11e8-9b0c-6eec28ca34cc.png)
![default](https://user-images.githubusercontent.com/21134578/44325858-86475a80-a48c-11e8-814a-e550ffa46e6f.png)
![default](https://user-images.githubusercontent.com/21134578/44325864-8ba4a500-a48c-11e8-9a4b-f2fff58eaa7b.png)

**Comment by xqxyxchy** [comment]
demo代码没有控制业务的并发导致的

**Comment by yu199195** [comment]
demo 的代码没有控制，demo的代码只是参考，你可以自己做下优化

**Comment by xqxyxchy** [comment]
已做优化处理；
建议加一些注解说明demo的业务未做并发处理，以免其他同仁误解；
提issue的时候没考虑到是业务本身的并发问题，提完就发现是业务并发这个问题；
