### ISSUE TITLE
提供者报未知异常，消息消费端不能set重试次数，会报npe

### ISSUE THREAD

**Issue by ChoviWu** [yu199195/myth#42]
mythTransaction.setErrorMsg(e.getCause().getMessage());
![image](https://user-images.githubusercontent.com/19967338/48698637-8a694c80-ec22-11e8-8335-4e132e520190.png)
图片已经上传到issues上，希望老大能把这个优化一下

**Comment by yu199195** [comment]
具体错误是什么？

**Comment by ChoviWu** [comment]
nullpointException，在mythTransaction.setErrorMsg(e.getCause().getMessage()); 的时候，e.cause()对象是null，所以该异常不能set进去，catch的时候抛出了npe，所以重试次数不再叠加

**Comment by yu199195** [comment]
e.cause() 为null？

**Comment by yu199195** [comment]
你可以改下，提供下pr这是最好的参与方式
