### ISSUE TITLE
持有过多的数据库连接不释放，导致数据库连接错误

### ISSUE THREAD

**Issue by yueru-mylove** [yu199195/myth#51]
[log-disruptor-2] o.d.m.c.s.r.JdbcCoordinatorRepository    : executeUpdate-> wait millis 60000, active 0, maxActive 100

**Comment by yueru-mylove** [comment]
执行事务补偿的时候每次都获取新连接，并且不释放，一段时间之后无法连接mysql

**Comment by yu199195** [comment]
myth没有补偿的概念，你是rpc挂了之后出现的么

**Comment by yueru-mylove** [comment]
> myth没有补偿的概念，你是rpc挂了之后出现的么

是配置出错，数据库没连接上。
