### ISSUE TITLE
适配一下最新的spring-amqp、spring-rabbit版本 最新版的部分类已经转义到其他package中

### ISSUE THREAD

**Issue by baibuxiha** [yu199195/myth#56]
最新版的spring-amqp已经把CorrelationData 已经从support包转移到connection中
https://github.com/spring-projects/spring-amqp/commit/91f79aa547bea487ce851050de3215a876728d92#diff-b7d7d12259936f90e48a6ed6984b7d53

**Comment by yu199195** [comment]
最新版本，改了，但是还有用户没用最新版本的
